### ISSUE TITLE
Keyboard navigation to parent

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#10]
It would be nice if there was an easy way to navigate to the parent node. For example by pressing "left" on keyboard. Currently there's no obvious way to do it — which makes navigation in a tree with deeply nested siblings challenging. (Recording is my unsuccessful attempt to find a parent node)

![screen recording 2019-02-27 at 04 36 pm](https://user-images.githubusercontent.com/810438/53507792-713d2b00-3ab0-11e9-8814-c1b10e4cba5e.gif)

**Comment by bvaughn** [comment]
Left arrow support added in 0153eae
