### ISSUE TITLE
Scroll to center for offscreen items only

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#104]
This is probably a feature request for `react-window`, but I want a different scrolling mode here:

https://github.com/bvaughn/react-devtools-experimental/blob/267ab34fbd713471fbf2da8e325c833e117c0a1f/src/devtools/views/Components/Tree.js#L56

First, a few motivating examples:

## Exhibit 1: Selection Sync

![Screen Recording 2019-04-09 at 01 39 am](https://user-images.githubusercontent.com/810438/55765701-dc432f80-5a68-11e9-95a0-5987e95d68c7.gif)

## Exhibit 2: Search

![Screen Recording 2019-04-09 at 01 40 am](https://user-images.githubusercontent.com/810438/55765702-e06f4d00-5a68-11e9-9e9f-3534b43612f4.gif)

## Exhibit 3: Find DOM Node

![Screen Recording 2019-04-09 at 01 41 am](https://user-images.githubusercontent.com/810438/55765706-e2391080-5a68-11e9-843a-55a68bf08b05.gif)

## Proposal

As you can see, the current behavior scrolls to nearest. This is what I want *when the item is already on screen*. However, if it's off screen, I want to *center* it — there's no benefit to me to seeing it at the bottom or at the top of the screen.

So I want a combination of `auto` (but only for onscreen items) and `center` (but only for offscreen items).

I'd be happy to PR this to `react-window`. Shouldn't be hard to combine the two behaviors.

**Comment by bvaughn** [comment]
> This is what I want when the item is already on screen. However, if it's off screen, I want to center it — there's no benefit to me to seeing it at the bottom or at the top of the screen.

What's the "benefit" of centering it?

To me, subjectively, scrolling the least amount possible to ensure it's visible is the least "jarring" change...but maybe I'm thinking about this incorrectly?

**Comment by gaearon** [comment]
The benefit is that if they’re sufficiently far away, you will perceive it as a jump anyway. Centering makes it subjectively easier to start working with it because you see the surrounding context.

I think that’s why Chrome’s tools center when you choose the DOM item on the page.

**Comment by gaearon** [comment]
I agree it shouldn’t center when they’re on the same virtual “page” though. I think that’s the concern you’re referring to?

**Comment by bvaughn** [comment]
I agree that it matters less if they're far away. I guess I'm thinking of when they're _close_ and we scroll e.g. 300px when we could have just scrolled 50px.

**Comment by bvaughn** [comment]
> I think that’s why Chrome’s tools center when you choose the DOM item on the page.

When we have a subjective disagreement, I'm happy to just follow precedent.

**Comment by threepointone** [comment]
I'm here to bother you brian, I agree with dan here. I'm increasingly using the crosshair to target elements, and the very first thing I always have to do is scroll a bit so I can see the element clearly. 

![image](https://user-images.githubusercontent.com/18808/55886566-e87fd780-5ba3-11e9-8515-eaaa649dac5d.png)

Note in the screenshot how that it's in the very corner of the panel.

I'll attempt a PR for this soon. I've been curious to contribute as well.

**Comment by bvaughn** [comment]
To clarify my previous comment, I'm happy to defer to Chrome's precedent here and make the change Dan's suggesting 😄

**Comment by bvaughn** [comment]
I believe you'er working on this, Dan.

**Comment by gaearon** [comment]
Yeah that would be https://github.com/bvaughn/react-window/pull/209 + https://github.com/bvaughn/react-devtools-experimental/pull/138

**Comment by bvaughn** [comment]
Cool. 😄 I just left that comment to explain why I was assigning the issue to you.

**Comment by gaearon** [comment]
Fixed in https://github.com/bvaughn/react-devtools-experimental/pull/138
