### ISSUE TITLE
Hard to tell if devtools is focused

### ISSUE THREAD

**Issue by sophiebits** [bvaughn/react-devtools-experimental#106]
In old devtools, the focused row becomes gray if your focus is not on the devtools:

![image](https://user-images.githubusercontent.com/6820/55766115-ef81db00-5a27-11e9-824f-d01dbc20baa3.png)

And blue when it is.

In new devtools, you can't tell if you're focused. This is frustrating. For example:

1. Click the inspect crosshairs button
2. Click an element in the page
3. Press Up or Down arrows to move the selection. It fails. (You think your selection is on the devtools but it's not!)

(Bonus feature request: If it is possible to focus the panel automatically after click-to-inspect, that would be awesome too.)

**Comment by gaearon** [comment]
Wanna take this? We planned to do it but haven’t gotten around to it yet.

**Comment by lucasecdb** [comment]
I can take this if no one is on it already.

**Comment by gaearon** [comment]
Sure.
