### ISSUE TITLE
Selecting DOM target should not pass clicks through

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#11]
I expect to be able to inspect an element without actually interacting with it. Since in many cases that would cause an undesirable action (such as with buttons and popups).

![screen recording 2019-02-27 at 05 01 pm](https://user-images.githubusercontent.com/810438/53508338-7353b980-3ab1-11e9-8c72-1938bf809c4f.gif)

**Comment by bvaughn** [comment]
Hm. I wouldn't expect clicks to be passed through, since [I'm calling `preventDefault` and `stopPropagation`](https://github.com/bvaughn/react-devtools-experimental/blob/89df0a6363d15a502b278a25b31a97706b4346c8/src/backend/agent.js#L210-L228).

**Comment by gaearon** [comment]
By that point it already reached the listeners, no?

You could stop it in the capture phase. But if possible, a more foolproof solution might be to have the overlay "eat" the events by the virtue of being on top instead of handling them at window level.

**Comment by bvaughn** [comment]
Yup, I just forgot to setup the listeners to use capture phase. Whoops.

**Comment by bvaughn** [comment]
Fixed in bf02b2f
