### ISSUE TITLE
Elements height being clipped by console

### ISSUE THREAD

**Issue by lucasecdb** [bvaughn/react-devtools-experimental#110]
![clipping-bug](https://user-images.githubusercontent.com/10223856/55770859-3984b400-5a5c-11e9-8ae4-e51ecf1e4f51.gif)

This one was kinda tricky to reproduce, but basically the steps are:

1. Click the inspect element and hover any component
2. Open the console pressing esc
3. Move mouse back to devtools and click again the inspect button (to stop inspection).
4. Close the console with esc.

(ps: sorry for the gif quality, I don't know how to properly convert the .mov to .gif)

**Comment by hristo-kanchev** [comment]
I can't seem to reproduce this. Is this still an issue?

**Comment by lucasecdb** [comment]
yeah, I just checked. The reproduction steps are a bit hard, because I can't find a consistent way to trigger the issue, but it is still happening :-/

**Comment by bvaughn** [comment]
When it happens, just open and close the secondary console again and that will "fix" things.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16486
