### ISSUE TITLE
Mouse interaction nitpicks

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#12]
1. I don't see the need for a hand cursor over the whole area. It's fairly obvious those are selectable, and they're not links. I would suggest a default cursor.

2. I would suggest focusing/selecting an element on mousedown rather than click. It's not a button. That's how selection works in Chrome elements, MacOS finder, text boxes, etc. It would also make right pane feel subjectively faster since it would start loading earlier.

![screen recording 2019-02-27 at 05 04 pm](https://user-images.githubusercontent.com/810438/53508635-055bc200-3ab2-11e9-8b9e-9dbc20d4b330.gif)

**Comment by bvaughn** [comment]
Fixed by 1e4434e

**Comment by gaearon** [comment]
Now it shows a "text" cursor over element name. Can we make it always show a regular pointer? (Relatedly, I'd probably disable the text selection in left pane because I trigger it too often accidentally)
