### ISSUE TITLE
Buttons jump during the loading state

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#13]
Maybe we could make them fixed (but noops) while it's loading data? Otherwise it flickers when navigating between many items.

![screen recording 2019-02-27 at 05 07 pm](https://user-images.githubusercontent.com/810438/53508770-51a70200-3ab2-11e9-8d97-ea5482614e52.gif)

**Comment by bvaughn** [comment]
Hm. Maybe I'll just show the view-source button but disable it. That way nothing will jump or pop.

**Comment by bvaughn** [comment]
Yeah, that feels nice.

Fixed in 05ef0ad
