### ISSUE TITLE
Bounding boxes don't include all children

### ISSUE THREAD

**Issue by sophiebits** [bvaughn/react-devtools-experimental#131]
Repro:

1. Hover EditableProps on https://react-devtools-experimental.now.sh/

Expected: Everything from the "Editable props" header through the list under "Forward Ref" is highlighted
Actual: Only the "Editable props" header is highlighted

I'm guessing it is only finding the first DOM node in the hovered component instead of all of them.

**Comment by gaearon** [comment]
Yeah, I think old DevTools has the same issue. Would be nice to fix.

**Comment by sophiebits** [comment]
Diagnosis:

This happens because highlightElementInDOM calls into findNativeByFiberID, which ultimately calls into React's findHostInstanceByFiber which only returns the first (like findDOMNode does). (findNativeByFiberID has some weird Suspense logic too, which I don't think belongs in devtools: https://github.com/bvaughn/react-devtools-experimental/pull/61/files#r274755172.)

To fix, I'd probably add another findHostInstance**s**ByFiber (plural) method in React's injectIntoDevTools that returns an array.

**Comment by sompylasar** [comment]
Sneak peek:
<img width="817" alt="Screen Shot 2019-04-20 at 11 48 02 PM" src="https://user-images.githubusercontent.com/498274/56466415-d3d2e900-63c6-11e9-9979-c475bb7d2716.png">

**Comment by sompylasar** [comment]
Also (can be in a separate PR but related) direction hint in the tooltip to see where to look for your elements:
<img width="818" alt="Screen Shot 2019-04-20 at 11 49 44 PM" src="https://user-images.githubusercontent.com/498274/56466437-27ddcd80-63c7-11e9-8d85-e75097032805.png">

**Comment by sompylasar** [comment]
PRs submitted:
- multiple highlights: https://github.com/bvaughn/react-devtools-experimental/pull/207
- arrow direction in the tooltip (builds on top of the highlights rework): https://github.com/bvaughn/react-devtools-experimental/pull/208

**Comment by sompylasar** [comment]
Thanks @sophiebits for the investigation and the suggested solution!
