### ISSUE TITLE
Firefox version doesn't work with Nightly Firefox

### ISSUE THREAD

**Issue by wldcordeiro** [bvaughn/react-devtools-experimental#136]
Looks like some permissions have changed in the upcoming version. I see these two attempting to load up the Firefox version. Figured I'd get it reported here just in case, it is the most unstable Firefox version so 🤷‍♂️ .

```
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
```

```
Reading manifest: Error processing permissions.1: Value "background" must either: must either [must either [be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], be one of ["bookmarks"], be one of ["history"], be one of ["find"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab", "tabs", "tabHide"], be one of ["browserSettings"], be one of ["cookies"], be one of ["downloads", "downloads.open"], be one of ["topSites"], be one of ["webNavigation"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["browsingData"], be one of ["devtools"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["pkcs11"], be one of ["geckoProfiler"], be one of ["sessions"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], be one of ["telemetry"], be one of ["theme"], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]```

**Comment by bvaughn** [comment]
If you're interested in tracking this down and submitting a PR to fix the [Firefox `manifest.json`](https://github.com/bvaughn/react-devtools-experimental/blob/master/shells/browser/firefox/manifest.json) that would be great

**Comment by bvaughn** [comment]
> Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

Regarding this error, I believe the 3.x DevTools shell also reports this warning. It's not that the extension "doesn't work" with nightly Firefox. It's just that Firefox in general only supports persistent background pages.

I guess the "fix" here is just to remove the unsupported option that Firefox is warning about.

**Comment by bvaughn** [comment]
My brain refuses to even try to parse that second warning.

**Comment by wldcordeiro** [comment]
I'll give it a try, I really want to load up the extension in Firefox 😆

**Comment by bvaughn** [comment]
I'd love to take advantage of the [auto-update functionality](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Updates), like I did with Chrome (#145) but I haven't been able to successfully generate an `*.xpi` file that Firefox will actually open without saying it's corrected. Supposedly the `web-ext` module (that we're already using to test Firefox) supports this, but I gave up earlier.

If you'd be interested in helping with this, we could ditch the `*.zip` format entirely?

**Comment by wldcordeiro** [comment]
I'm looking at it now, just cloned the repo and I was asking around in the irc channels Mozilla says are for the extension devs. Gonna try to do the permission fix as one PR and then look into a follow up for updates/xpi support.

**Comment by bvaughn** [comment]
Sweet. If we could get an XPI generated (that Firefox doesn't say is corrupted or invalid) then we could add the update JSON format Mozilla requires to that deployment too and have auto-updates working for both browsers.

**Comment by bvaughn** [comment]
I _think_ this issue title may be misleading. I think the extension _does_ work in Firefox nightly. It  just logs a few console warnings.
