### ISSUE TITLE
Don't show search navigation when there's no search

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#14]
Seems a bit cluttering when they're unused:

<img width="149" alt="screen shot 2019-02-27 at 5 10 18 pm" src="https://user-images.githubusercontent.com/810438/53508902-99c62480-3ab2-11e9-9527-6ce349893238.png">

The feature I *do* wish was there (when not searching) is some kind of back-forward navigation between last selected items there. But that's more of a feature request.

**Comment by bvaughn** [comment]
I don't agree with this suggestion. I patterned this UI after the browser's own find-in-page UI.

**Comment by gaearon** [comment]
Right, but you only see the browser UI when you press Cmd+F. It's not permanently visible when you didn't mean to search.

**Comment by bvaughn** [comment]
I think I still disagree with this, but I'll let it sit a bit and see if my mind changes 😄

**Comment by gaearon** [comment]
Maybe you can show if `search !== '' || isFocused` :-)

**Comment by bvaughn** [comment]
This doesn't feel like a positive change to me. At best it feels subjective.

It feels wrong how the "x" button pops in or out under your cursor:
![aaakapture 2019-02-27 at 13 20 13](https://user-images.githubusercontent.com/29597/53523735-6e334200-3a92-11e9-8d8e-3eafd0d96b5b.gif)

For now I'm going to pass on this suggestion 😄 Maybe will revisit it later.
