### ISSUE TITLE
Commit picker should register leaving the picker at a side as setting a terminal value

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#141]
Seems non-ideal. Typically range controls handle this case.

![Screen Recording 2019-04-12 at 07 54 PM](https://user-images.githubusercontent.com/810438/56059844-0e041100-5d5d-11e9-892c-f3872414ffaa.gif)

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16492
