### ISSUE TITLE
Misalignment of borders

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#143]
Look at the borders closely:

* There's an unwanted horizontal gap between the left and right pane border close to the "Inspect" button
* The horizontal lines don't line up

<img width="558" alt="Screen Shot 2019-04-12 at 21 01 13" src="https://user-images.githubusercontent.com/810438/56063059-262c5e00-5d66-11e9-959f-181e6831fee6.png">

**Comment by bvaughn** [comment]
Fixed in b2cf896. I had just fat-fingered where the padding was when I re-added it.
