### ISSUE TITLE
Expand objects in right pane on single label click

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#144]
Currently you either have to click the arrow once, or click the label twice. I haven't seen double-clicks much in web UIs. It also doesn't match how Chrome object inspect works (which lets you click the property name once to expand). I think we should make a single click work.

**Comment by bvaughn** [comment]
The click+double click behavior was modeled after Chrome's Elements pane. I guess the "Computed" props side panel is single click to expand though so I don't really care if we change the side panel to follow it.
