### ISSUE TITLE
Vertical scrollbar is incorrectly positioned

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#151]
I'm at the very end of the tree. And yet scrollbar makes it seem like there's more to scroll. This repro is from the fixture but I got confused in a real product tree.

<img width="712" alt="Screen Shot 2019-04-13 at 16 41 39" src="https://user-images.githubusercontent.com/810438/56081964-1adf3e00-5e0b-11e9-99b7-67d32e9efc2d.png">

**Comment by bvaughn** [comment]
I don't think we can really fix this, can we? It's just the native browser scrollbar. The reason it doesn't go all the way to the bottom is that it leaves space for the horizontal scrollbar. (For the same reason, that one won't scroll all the way to the right.) This is just one of the many shitty aspects of scrollbars I think.

**Comment by gaearon** [comment]
Hmm, I thought that with virtualization it depends on `scrollHeight`? Tbh my last memories of dealing with scrollbars date to 2014 so I don't actually remember how they work. I'll take a closer look later.

**Comment by bvaughn** [comment]
Run this code in your browser:
```js
document.body.innerHTML = `
  <div style="width: 200px; height: 200px; border: 1px solid black; margin: 1rem; overflow: auto;">
    <div id="container" style="width: 300px;" />
  </div>
`;
const container = document.getElementById('container');
for (let i = 0; i < 100; i++) {
   container.innerHTML += `Line ${i}<br/>`;
}
```

You can verify that the same scroll thumb positioning behavior exists.

**Comment by bvaughn** [comment]
Scroll bars suuuuuck 👍

**Comment by gaearon** [comment]
Ahh because it's horizontally scrollable. Makes sense.
