### ISSUE TITLE
Investigate internal perf issue when toggling Suspense

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#157]
Profiles show we're spending a lot of time in the `renderer.js` code. Curious if there's some bad loop condition there.

**Comment by bvaughn** [comment]
I'd be curious how it compares to the legacy DevTools. (Wondering if it's necessarily slow because of how we have to walk-and-diff or if we're doing something dumb)

**Comment by gaearon** [comment]
First look: we're spending a *lot* of time messing with the typed array on mounting a large tree as a result of an update. I wonder if we could avoid re-creating it on every operation, and instead buffer them in a mutable array.

<img width="558" alt="Screen Shot 2019-04-15 at 2 19 29 PM" src="https://user-images.githubusercontent.com/810438/56135887-8ea75500-5f89-11e9-9f60-e3b07205f4c9.png">

**Comment by gaearon** [comment]
First improvement: https://github.com/bvaughn/react-devtools-experimental/pull/159
