### ISSUE TITLE
Don't lose tree position when exiting the focused mode

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#16]
It would be nice to stay on the last selected component. Currently it seems like we're jumping to the initial empty state. I just want to exit the mode — not lose the selection context.

![screen recording 2019-02-27 at 05 14 pm](https://user-images.githubusercontent.com/810438/53509218-47d1ce80-3ab3-11e9-981c-856e9ace5981.gif)

**Comment by bvaughn** [comment]
Totally understand why this feature would be nice to have.

That being said, I don't think I'm going to try to accommodate this request. (I don't want to maintain a stack of selected indices/ids.) The reducer in question is already super complicated. Reseting selected state was a conscious decision I made to try and avoid edge-case bugs or extra complexity.
