### ISSUE TITLE
Bugs when everything is collapsed by default

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#167]
I wanted to experiment with a UI that's collapsed by default.

But just flipping this to `true`:

https://github.com/bvaughn/react-devtools-experimental/blob/85179fe4a7e7cb2e9d79733eec4839443393e7ba/src/devtools/store.js#L604

creates weird visual artifacts:

<img width="402" alt="Screen Shot 2019-04-16 at 7 48 28 PM" src="https://user-images.githubusercontent.com/810438/56236225-01dfc280-6081-11e9-9b1a-cfac58775b9e.png">

Would be cool to fix it, at least just for experimentation.

**Comment by bvaughn** [comment]
I'm not seeing any "weird visual artifacts" after a quick initial test. Were you doing anything specific before they showed up?
