### ISSUE TITLE
Fix checkbox alignment

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#17]
Seems a bit weird to me it's centered.

<img width="435" alt="screen shot 2019-02-27 at 5 19 19 pm" src="https://user-images.githubusercontent.com/810438/53509520-dd6d5e00-3ab3-11e9-896c-0a0cfa664912.png">

This also looks odd:

<img width="401" alt="screen shot 2019-02-27 at 5 20 23 pm" src="https://user-images.githubusercontent.com/810438/53509580-fd9d1d00-3ab3-11e9-8337-c51798337583.png">

**Comment by bvaughn** [comment]
Uh...weird. That's not what I see. What browser and version?

![screen shot 2019-02-27 at 9 20 29 am](https://user-images.githubusercontent.com/29597/53509599-f43e9100-3a70-11e9-84b0-996bb542c434.png)

**Comment by gaearon** [comment]
Latest Chrome, Ads creation flow.

**Comment by bvaughn** [comment]
Weird. I also have the latest Chrome. Checkboxes are all properly left aligned for me. Whaaaat

**Comment by bvaughn** [comment]
Can you see if 13ca373 fixes this issue? I can't repro it so it's hard to confirm.

**Comment by gaearon** [comment]
Yeah that fixed it. Thanks.

**Comment by bvaughn** [comment]
Great, thanks
