### ISSUE TITLE
Toggling Suspense while searching creates dead search results

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#176]
1. Search for Suspense
2. Get to the one inside NestedSuspenseTree
3. Toggle it a few times

Note how the search results keep increasing on every toggle. Something isn't getting cleaned up. On large trees, this bug slows down UI to a crawl.

![Screen Recording 2019-04-18 at 03 16 PM](https://user-images.githubusercontent.com/810438/56367405-16d96480-61ed-11e9-9327-e55ec4d70415.gif)

**Comment by bvaughn** [comment]
Ooh yeah, this messes up our tree huh. Nice catch.
