### ISSUE TITLE
Include line numbers

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#18]
We know line numbers for some elements through JSX `__source`. Can we surface that? I think current DevTools does that for currently selected element although not 100% sure.

Maybe in the owner stack somehow.

**Comment by bvaughn** [comment]
Yes, the current DevTools does surface this information in the lower right hand corner:
![screen-shot-2019-02-28-at-2 53 24-pm](https://user-images.githubusercontent.com/29597/53604308-e9672780-3b68-11e9-84c3-d493a495b1b1.gif)

But what value does it add over being able to click the "View source" button and jump directly to the component definition?

![view-source](https://user-images.githubusercontent.com/29597/53604396-3a771b80-3b69-11e9-9370-bd95a6497320.gif)

I guess I'm not convinced it's necessarily worth the screen real estate it would take up.

**Comment by gaearon** [comment]
In the React Native version I think right-click actually opens the IDE? Not on the web though.

Note the view source is different. It shows you the *component definition*. But this line is the *element definition*. Kind of like the first owner.

Which is to say — maybe owner info could have line numbers somehow?

**Comment by bvaughn** [comment]
I guess I still don't understand..why is the element definition useful?

**Comment by bvaughn** [comment]
> In the React Native version I think right-click actually opens the IDE? Not on the web though.

In RN for the new DevTools the <> button will open the IDE.

**Comment by gaearon** [comment]
>why is the element definition useful?

You can see what caused this element to appear. For example, for a div you can see *which div exactly* it is in the component that rendered it. (I guess we don't show divs anymore so that's less useful.)

Really, all I'm saying is: do you think it would be useful to add line numbers to the owner stack?

**Comment by bvaughn** [comment]
> Really, all I'm saying is: do you think it would be useful to add line numbers to the owner stack?

Gotcha. I'm saying that I _don't_ think it would be that useful, but I'm trying to understand how you'd use it to see if I'm overlooking something.

I would guess that jumping to the source/definition of the owner component should probably be sufficient in most cases (unless it's a huuuuuge component).

My concern is that the source location information is something we only have for "inspected" fibers. (It isn't sent as part of the tree, but rather something the frontend has to ask for async.) It would require adding some complexity to fetch it for all of the owners in the stack, so it's something I would prefer _not_ to do unless there's a strong use case. 😄

**Comment by gaearon** [comment]
Fair enough

**Comment by rosswaycaster** [comment]
Yeah, I am really missing this feature in the new dev tools. I used to be able to highlight the element in dev tools and it would tell me where the specific element lived in my code. Very useful if you have multiple buttons on a page and need to know the line number to look at in the code for that button. From what I can tell clicking <> just takes me to where that button component is defined.

**Comment by bvaughn** [comment]
@rosswaycaster File location info is available in the console, in `$r`.

Otherwise please just check out this issue https://github.com/facebook/react/issues/16497
