### ISSUE TITLE
Experimental dev tools are not compatible with script-src 'nonce' Content Security Policy

### ISSUE THREAD

**Issue by charrondev** [bvaughn/react-devtools-experimental#183]
## The issue

When using an inline script content security policy react dev tools does not function at all.

Looking a little bit deeper, this seems to just be a non-production build of webpack. If this is the type of issue, that occurs because it's a development build of `backend.js`, then it's not really a significant issue.

## To reproduce

I've created a simple reproduction repo here https://github.com/charrondev/react-devtool-CSP-repro.

1. Clone the repo.
2. Run `npm run start`
3. Go to https://localhost:9000
4. Load React Dev Tools 3.x
5. Notice things work correctly.
6. Load React Dev Tools 4.x
7. Notice the dev tools do not load correctly.

**Expectation**

The dev tools load, even with this content security policy set.

**Comment by bvaughn** [comment]
Looks like I deployed a development build of DevTools to now.sh - (locally created) production build works fine. I'll fix this momentarily!

**Comment by bvaughn** [comment]
Pushed a new (production) build that should resolve this problem 👍 Thanks again for the report
