### ISSUE TITLE
Glitchy freezing when searching for 'Suspense' before app loads

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#185]
1. Take a large app
2. Search for 'Suspense' fast
3. Start pressing "Enter"
4. The app loads, leading to a several second long stall with glitchy DOM highlighting

**Comment by bvaughn** [comment]
Does this eventually recover?

**Comment by bvaughn** [comment]
Haven't seen this (or heard anything about it) for a while so I'm going to close. Let's re-open if we see it happening again.
