### ISSUE TITLE
Long string in props gets cut off

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#19]
Pretty sure this string isn't shown/wrapped fully. It seems like it goes outside the screen but I can't scroll it either.

<img width="417" alt="screen shot 2019-02-28 at 2 04 53 pm" src="https://user-images.githubusercontent.com/810438/53571903-e452aa00-3b61-11e9-8c47-2ec617337db5.png">

**Comment by bvaughn** [comment]
Ugh. I don't understand what's different about your Chrome and mine. This isn't how things look in mine. The text properly wraps with the correct right padding.

**Comment by bvaughn** [comment]
Can we screenshare sometime? So I could look at what's going on in Chrome's devtools?

**Comment by reznord** [comment]
@bvaughn this is a small css issue which happens when we resize the window and we won't be able scroll horizontally through the attributes section (need to add `word-break: break-all` to the values field).

Can send a quick fix for this 🙃

**Comment by bvaughn** [comment]
Cool. It's weird since I'm not able to repro it, but yes I'd love a fix if you would be willing to either open a PR or leave a diff comment here.

**Comment by reznord** [comment]
done :)

**Comment by bvaughn** [comment]
Pushed out an updated build to the demo site.
