### ISSUE TITLE
Light mode inactive selection is too low contrast

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#190]
It's important for it to be visible because it is inactive when you select by DOM node. But the grey is too light and is hard to see. Let's bump up the grey to be darker.

**Comment by bvaughn** [comment]
Ok. I'll change it.

### before
<img width="265" alt="Screen Shot 2019-04-18 at 6 18 15 PM" src="https://user-images.githubusercontent.com/29597/56400016-5eb8b580-6206-11e9-9230-cea9dd9b3c00.png">

### after
<img width="278" alt="Screen Shot 2019-04-18 at 6 18 18 PM" src="https://user-images.githubusercontent.com/29597/56400017-5eb8b580-6206-11e9-9e7c-2f9611b11fed.png">

### chrome (for comparison)
<img width="344" alt="Screen Shot 2019-04-18 at 6 18 20 PM" src="https://user-images.githubusercontent.com/29597/56400018-5eb8b580-6206-11e9-8ebd-6024d528b60d.png">

**Comment by bvaughn** [comment]
f286c0d
