### ISSUE TITLE
Clarify empty values in right pane

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#20]
Are `error`, `target`, `shimhash`, `children[1]` nulls? Undefineds? Empty strings? Would be cool if there were clarifying hints for empty values.

<img width="191" alt="screen shot 2019-02-28 at 2 06 28 pm" src="https://user-images.githubusercontent.com/810438/53571982-1e23b080-3b62-11e9-8164-8ae627fac5bf.png">

<img width="214" alt="screen shot 2019-02-28 at 2 06 41 pm" src="https://user-images.githubusercontent.com/810438/53571980-1e23b080-3b62-11e9-8ac3-f2c7f83bd547.png">
<img width="157" alt="screen shot 2019-02-28 at 2 06 34 pm" src="https://user-images.githubusercontent.com/810438/53571981-1e23b080-3b62-11e9-828b-ad39d274dee4.png">

**Comment by bvaughn** [comment]
Ah, good point I guess. I can use placeholders to help here.
![screen shot 2019-02-28 at 10 44 24 am](https://user-images.githubusercontent.com/29597/53590094-e0189380-3b45-11e9-9a77-4de9154daaf7.png)

**Comment by bvaughn** [comment]
bffa72c
