### ISSUE TITLE
Feedback: new DevTools filter out the host nodes (e.g. DOM elements) from the Components tree, making it hard to debug rendering of said nodes

### ISSUE THREAD

**Issue by sompylasar** [bvaughn/react-devtools-experimental#211]
## Background

It's often necessary to debug native (host) elements rendered by
the components, but the new version of DevTools removed this functionality.

The reasoning for this feature to exist:

> I want to do the reverse: from the tree find where are my elements.
> Not every element that gets rendered is visible and of clickable size.
> https://twitter.com/sompylasar/status/1118580156430311424
> https://twitter.com/dan_abramov/status/1118486315736158208

### Use cases

- Developing low-level components that render host nodes directly.
  - Sometimes on top of that do some non-trivial manipulation with them like size and position measurement, `IntersectionObserver`, `React.Portal`.
  - Debugging component layouts when it's important how the components and the host nodes nest within each other, which component a host node belongs to.
  - Simple examples: 
    - `<Link>` that renders an `<a>`;
    - `<Button>` that renders either `<button>` or `<a>` depending on props.
  - Complex example:
    - components with `display: table`, `display: flex`, or `display: grid` where certain nesting of host nodes is required;
    - `<Video>` that composes and manipulates a `<video>` and/or `<canvas>` and/or `<img>` in a non-trivial manner (like cross-fade, positioned controls, offscreen in-DOM buffers, moving/reparenting specific host nodes around);
    - anything positioned and animated using the DOM/CSSOM directly, not `react-spring` or something.

## Suggested solution

Make the visibility of host nodes optional, hidden by default, switch to visible available in the Settings, the setting is persisted across page reloads.

A proposed implementation for getting this feature back: https://github.com/bvaughn/react-devtools-experimental/pull/210

### Pros

- reduced need to switch to the Elements tab
- the tree resembles what actually gets on screen
- for low-level components that render host nodes the tree resembles what's in the code as well
- elements that are invisible or of zero size can be seen and inspected from Components

### Cons

- more elements in the Components tree: more cognitive load (resolved by optional visibility)
- more elements in the Components tree: worse performance (maybe non-issue?)
- one more option (true/false) to maintain, test
- more visual variants of Components to maintain (conditional rendering, conditional logging for inspection, theme colors)

**Comment by sompylasar** [comment]
Updated the description 👆

**Comment by bvaughn** [comment]
We'll include this as part of a broader filtering initiative, #231.

**Comment by bvaughn** [comment]
Resolved!
