### ISSUE TITLE
Deeply nested hooks

### ISSUE THREAD

**Issue by olee** [bvaughn/react-devtools-experimental#214]
The dehydration kills hooks information after only about 3 levels, preventing debugging of mobx-react-lite observable components, because the call-stack is nested quite deeply there:
![image](https://user-images.githubusercontent.com/6547794/56597591-137e1880-65f3-11e9-9158-14133498059a.png)

I noticed that I can increase `LEVEL_THRESHOLD` to prevent this issue:
![image](https://user-images.githubusercontent.com/6547794/56597313-82a73d00-65f2-11e9-87a8-6be26671c0f9.png)

However I don't think that this is the proper approach so I would like to ask, why is the hooks stack cut off at all after a few levels of nesting?
What's the reason this dehydration is necessary?

**Comment by bvaughn** [comment]
It's not a hooks-specific thing. It affects props and state as well.

> What's the reason this dehydration is necessary?

To avoid the performance costs of serializing deep property chains. Serialization can be fairly expensive, especially when there are a lot of props/state/context.

We might need to come up with a lazy-hydration strategy for fetching values that get truncated, although I'm not sure how that will work yet.

**Comment by bvaughn** [comment]
This issue seems like  a question, I guess. Now that it's been answered, I'm not sure what to do with it.  I suspect we won't be removing hydration entirely. 😄I think I'll close this issue and create a hydration umbrella issue to generally discuss technical strategies.

**Comment by bvaughn** [comment]
#216

**Comment by olee** [comment]
Well, increasing the default level of 6 to maybe like 20 would already help a lot.
Also wouldn't it be an option to just drop dehydration for hooks?
They are only fetched when an element is selected and even with large components and deep nesting, I don't think that this small amout of data is too much to handle.

**Comment by bvaughn** [comment]
> Also wouldn't it be an option to just drop dehydration for hooks? They are only fetched when an element is selected even with large components and deep nesting, I don't think that this small amout of data is too much to handle.

The new DevTools only fetches any props/state/context/hooks for the selected element, and there is some throttling too. There's still potentially a lot of other traffic going across the bridge, and serialization itself can be slow for large pieces of data. Limits like this are put into place to help with extreme cases, like #195
