### ISSUE TITLE
Hydrate dehydrated values

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#216]
Before sending an inspected element across the bridge, DevTools truncates nested properties that are deeper than a certain threshold to avoid the performance costs of serializing deep property chains. (Serialization can be fairly expensive, especially when there are a lot of props/state/context.)

The legacy DevTools also did this, but it provided a mechanism to (async) request "dehydrated" values  to be "hydrated" on-demand so they could be inspected. This was kind of a crappy experience with values that change frequently (e.g. hooks) since expanded nodes would often re-collapse when the fiber was updated (e.g. https://github.com/facebook/react-devtools/issues/1335)

We should re-think this feature in the new DevTools. How should dehydration work? How will it work with hooks in particular? (The renderer interface would need to be stateful.)

Maybe we could also increase the threshold beyond the current 6 (since we are already lazily inspecting, and throttling, etc)

**Comment by gaearon** [comment]
>This was kind of a crappy experience with values that change frequently (e.g. hooks) since expanded nodes would often re-collapse when the fiber was updated 

Btw this doesn't sound like an inherent problem to updating them, does it? It should be perfectly possible to update them without losing the expansion state.

**Comment by bvaughn** [comment]
Let's say we get an object that looks like this (where B's contents have been dehydrated):
```
A
└── B
    └── …
```

Then we expand it and hydrate it:
```
A
└── B
   ├── D
  └── D
```
Now we get an update from the backend which has B's contents dehydrated again:
```
A
└── B
    └── …
```

What do we do? We could try to merge the results and assume that B's contents haven't changed, but what if they have? We'd be showing torn state.

Another alternative would be to expand the inspect API to include a list of previously hydrated props and change the serialization logic to _not_ dehydrate those paths on update.

**Comment by gaearon** [comment]
Thanks for explaining! In this case, can we... suspend? If we read on deeper level than we currently are. And request hydration.

**Comment by bvaughn** [comment]
We could, but I think in practice that might be a janky user experience. What would we show in the fallback state? A loading spinner would be pretty jarring if it actually appeared. We could temporarily show the previous hydrated state, but then I think maybe the UI would not be interactive in any meaningful way while we were suspended?

Seems like we'd probably want to let the backend know to just send the full update for the dehydrated paths too, whatever that would look like. Seems doable, but it would need a little thought and exploration.

**Comment by gaearon** [comment]
>We could temporarily show the previous hydrated state, but then I think maybe the UI would not be interactive in any meaningful way while we were suspended?

This sounds like the busy spinner pattern. It doesn't need to literally be a spinner — we could grey out the object a bit or show "..." next to what you clicked. We won't be suspended for seconds, right?

**Comment by bvaughn** [comment]
Oh look. This is already done.
