### ISSUE TITLE
Disable text selection in elements pane

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#22]
Seems like this is not very useful. I keep doing it by accident.

<img width="299" alt="screen shot 2019-02-28 at 5 31 12 pm" src="https://user-images.githubusercontent.com/810438/53585808-ae6fee80-3b7e-11e9-8cfa-ff9737a1b99a.png">

Can we disable selection and make the cursor a pointer instead of a text caret?

**Comment by bvaughn** [comment]
d34a32d
