### ISSUE TITLE
Crashes and warnings when quickly collapsing

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#228]
This is weird. Happens if I select a node deeply and then long-press "left" arrow.

```
Invalid index 154 specified; store contains 154 items.

Uncaught Invariant Violation: Expected to find a host parent. This error is likely caused by a bug in React. Please file an issue.
    at ReactError (file:///Users/gaearon/p/react-devtools-experimental/shells/dev/build/devtools.js:8529:40)
```

It starts with "invalid index" and then gives me different React invariants or warnings depending on how lucky I am.

![Screen Recording 2019-04-25 at 05 58 PM](https://user-images.githubusercontent.com/810438/56754075-fcbafb80-6783-11e9-8fe6-84aa29d1c120.gif)

**Comment by gaearon** [comment]
More weird symptoms:

<img width="889" alt="Screen Shot 2019-04-25 at 6 38 22 PM" src="https://user-images.githubusercontent.com/810438/56756281-5671f480-6789-11e9-8d0b-631a5217e63b.png">

**Comment by gaearon** [comment]
Huh.

<img width="832" alt="Screen Shot 2019-04-25 at 6 41 37 PM" src="https://user-images.githubusercontent.com/810438/56756492-c7191100-6789-11e9-8814-cb849590ee01.png">

**Comment by gaearon** [comment]
This "fixes" it:

```js
       runWithPriority(UserBlockingPriority, () => dispatch(action));
-      next(() => dispatch({ type: 'UPDATE_INSPECTED_ELEMENT_ID' }));
+      runWithPriority(UserBlockingPriority, () => dispatch({ type: 'UPDATE_INSPECTED_ELEMENT_ID' }));
     },
```

So I suspect it's a bug with `Scheduler.next()`.

**Comment by gaearon** [comment]
This also looks funky. Note how somewhere in the middle right pane gets "stuck" showing the same cycle of values:

![Screen Recording 2019-04-25 at 07 36 PM](https://user-images.githubusercontent.com/810438/56759733-8b824500-6791-11e9-95ba-d4d3630a4c5e.gif)

**Comment by gaearon** [comment]
React bug: https://github.com/facebook/react/issues/15512

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16487
