### ISSUE TITLE
Right-align Profiler Flame Graph Children

### ISSUE THREAD

**Issue by sebmarkbage** [bvaughn/react-devtools-experimental#236]
This a bit hard to explain in words but when looking at the flame graph. I realized that the "self time" is basically the distance from at the right most end of a horizontal bar to the right most end of the children.

This made the graph feel counter-intuitive to me because I think of it as a kind of timeline going from left to right.

The self-time of a component is always *before* its children but it felt like it was executing something after all of the children since this time is on the right most side.

If instead the children aligned to the right most edge of its parent, that way the empty space would show before the parent.

This would more closely mimic a timeline graph where self-time in the beginning of a function is on the left side of the time spent in children.

**Comment by bvaughn** [comment]
Interesting suggestion. For what it's worth, I tried right-aligned initially and didn't like it as much, but I actually kind of like the idea given this reasoning. Let's give it another try and see.

**Comment by bvaughn** [comment]
I have mixed feels.

![Screen Shot 2019-05-03 at 9 16 33 AM](https://user-images.githubusercontent.com/29597/57150963-8a9a7600-6d84-11e9-87cb-a6ed027b289a.png)

**Comment by bvaughn** [comment]
Feedback is overwhelmingly in favor of this change. Let's do it.
