### ISSUE TITLE
Add highlight updates feature

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#244]
![highlight-updates-Kapture 2019-04-29 at 8 43 58](https://user-images.githubusercontent.com/29597/56908381-0cc02d00-6a5b-11e9-9dbb-31eb58638f45.gif)

**Comment by submetu** [comment]
Hi, wondering about the design of the that you guys have in mind for PREFERENCES.

Is it gonna go here?
![image](https://user-images.githubusercontent.com/18688941/57865348-19d46e80-7806-11e9-8881-3e4b26d59643.png)


Also, I would like to take this issue if you think it's doable?

**Comment by bvaughn** [comment]
I've been working adjacent to this feature on the Profiler updaters highlight recently, so it would probably be easier if I just work on this one. Thanks though.

**Comment by submetu** [comment]
👍

**Comment by bjankord** [comment]
This would be a great feature to carry over from the current react-dev-tools, hoping to see this added to the react-devtools-experimental project :+1:

**Comment by bvaughn** [comment]
Migrating issues to github.com/facebook/react

Looks like this one has already been filed: https://github.com/facebook/react/issues/16437
