### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated warning

### ISSUE THREAD

**Issue by hanneswidrig** [bvaughn/react-devtools-experimental#249]
![image](https://user-images.githubusercontent.com/3399497/56987470-82abbd80-6b5b-11e9-84a4-ad0f1ce50f80.png)

I apologize if this is a duplicate, I am sure it is known. Using Edge Insider, I am receiving these warning/errors.

**Comment by bvaughn** [comment]
The only browsers this extension supports are Chrome and Firefox. I had no idea that Edge could even load it.

The extension only uses sync XHR to support "reload and profile" by the way. Are you using that feature?

**Comment by hanneswidrig** [comment]
Edge Insider is based on Chromium 76. I do use the "reload and profile" feature sometimes, if it's supposedly to automatically detect when the page finishes loading, like the built-in Chrome devtools, that's not working in either Chrome 74 or Chromium 76.

I get the same warning in Chrome 74, so I don't think it's Edge Insider specific.

**Comment by bvaughn** [comment]
Ah. I misread your initial report. I thought you were saying it was a runtime error in Edge.

Yes, the warning is logged in Chrome too- but there is no other way for an extension to eagerly inject a script into the context of a website without using sync XHR. If you're interested in more background info, check out PR #35.

I spoke with a Chrome extension dev rel (@DotProto) about this issue. My take away was that he agreed this was a reasonable use of sync XHR, and he did not think it was likely that support would be removed without the Chrome team first offering an alternative API for this.

**Comment by hanneswidrig** [comment]
Looks like adding `-url:chrome-extension://nfbeoglmnmcfolbonpjonlgageflmghb/build/injectGlobalHook.js`  in the Chome Dev Tools console is the only way to suppress the warning.

**Comment by bvaughn** [comment]
To me, this has the feel of a browser bug (in that there's no API for performing a valid use case). I don't think there's any action we can take on our side other than alert the Chrome folks (which we've done)

**Comment by SimantoR** [comment]
I came across the same error in Firefox on MacOS 10.15.2
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ lpfulllib.js:1:35316`

This is the execution code inside React 16.12. Disclaimer, I tried to make it asynchronous with promise.
```
const onRegister = (
  e: React.FormEvent<HTMLFormElement>
) => {
  e.preventDefault();
  return new Promise<void>(
    (resolve, reject) => {
      fetch("http://localhost:3001/register", {
        method: "POST",
        body: JSON.stringify(user),
      })
        .then(async (response) => {
          if (response.status === 202) {
            setStatus("User Added!");
          } else if (response.status === 400) {
            setStatus(await response.text());
          } else {
            reject(response.status);
          }
          resolve();
        })
        .catch(reject);
    }
  );
};
```
