### ISSUE TITLE
Searching sometimes selects root node

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#26]
This seems to happen if I open DevTools before the page fully loads.
Then searching will select first root instead of first matching element.

![screen recording 2019-03-01 at 02 10 pm](https://user-images.githubusercontent.com/810438/53643399-db2e0f80-3c2b-11e9-9058-a8ab6336278f.gif)

**Comment by bvaughn** [comment]
Probably a bug in my reducer logic somewhere.
