### ISSUE TITLE
Component selector should be Flare compatible

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#282]
DevTools currently relies on `preventDefault` and `stopPropagation` to prevent the selector tool from actually clicking on a DOM element:

https://github.com/bvaughn/react-devtools-experimental/blob/eaaeb439b4d80e72892b897d900568f8cf77ca9c/src/backend/agent.js#L484-L490

Flare does not work with this, so you can't select a component without also potentially changing it in a significant way. We should find a way to fix this!

cc @trueadm

**Comment by trueadm** [comment]
cc @necolas

**Comment by trueadm** [comment]
With Flare, we could provide a prop to <Press> that always does preventDefault and stopImmediatePropagation. Would that be a solution?

**Comment by bvaughn** [comment]
Seems like it could work, yeah. So long as we could identify when to use the Flare approach vs the normal/synthetic event approach.

**Comment by trueadm** [comment]
Maybe I have got this wrong though. Is this using Flare from within dev tools, or when dev tools interacts with a page using Flare? If the later, then my point above won’t work. Let me think about how to do that.

**Comment by bvaughn** [comment]
Check out the code snippet I linked to in the bug description.

Essentially, DevTools needs a way to identify that the user has clicked on a DOM element without the event slipping through to the element itself.

We're already using capture:
https://github.com/bvaughn/react-devtools-experimental/blob/eaaeb439b4d80e72892b897d900568f8cf77ca9c/src/backend/agent.js#L375-L378

**Comment by trueadm** [comment]
Ah, maybe it’s as simple as using pointer events here instead of mouse events? Given the only browser that doesn’t support pointer events is Safari, this should be fine as dev tools isn’t supported on safari.

**Comment by trueadm** [comment]
@bvaughn Actually, I just checked. This should be fine – as we're attaching event listeners in dev tools to the `window`, whilst Flare attaches them to the `document`. On closer inspection, `window` events always fire first, so I'm not sure why we're seeing issues here, other than maybe you're using `stopPropagation`. If you try using `stopImmediatePropagation()` does that fix this issue?

**Comment by bvaughn** [comment]
> If you try using `stopImmediatePropagation()` does that fix this issue?

Will check (when I get the chance) and report back.

**Comment by trueadm** [comment]
I've updated my reply but that should work. :)

**Comment by bvaughn** [comment]
Thansk!
