### ISSUE TITLE
Unable to report issue with "Report this issue" link

### ISSUE THREAD

**Issue by daltondowning** [bvaughn/react-devtools-experimental#284]
STR:

1. Intentionally throw an error in the Profiler component.
2. Open React DevTools Profiler. The error you threw should appear.
3. Click the "Report this issue" link in the error view.

The link takes me to the following URL:

`chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/https///github.com/bvaughn/react-devtools-experimental/issues/new?<details about the issue>`

Version: `4.0.0.3 f47b40f`

**Comment by daltondowning** [comment]
Looks like the `replace(':', '/')` invocation in `getGitHubURL` is causing the issue. Removing that invocation resolved the issue for me.

**Comment by bvaughn** [comment]
Can't reproduce the behavior you're reporting.

What OS?

**Comment by bvaughn** [comment]
For me, `git remote get-url origin` returns "git@github.com:bvaughn/react-devtools-experimental.git"

So the current sequence... https://github.com/bvaughn/react-devtools-experimental/blob/34f6fa4fab502497b6ffd5d04cf0547bb9569fc2/shells/utils.js#L11-L19

Transforms the string like so:
1. Initial `git@github.com:bvaughn/react-devtools-experimental.git`
2. Replace ":" `git@github.com/bvaughn/react-devtools-experimental.git`
3. Replace "git@" `https://github.com/bvaughn/react-devtools-experimental.git`
4. Remove ".git" `https://github.com/bvaughn/react-devtools-experimental`

**Comment by bvaughn** [comment]
I'm also assuming (although you didn't specify) that you reproduced this error running the DevTools dev shell locally, rather than using the (released) extension?

I'm also assuming that maybe you used HTTPS to clone the repo rather than SSH?

**Comment by bvaughn** [comment]
I updated the function to handle HTTPS clones. 395c025

**Comment by daltondowning** [comment]
I used HTTPS to clone and built the extension locally. Sorry for leaving those important details out. Thanks for the quick fix.
