### ISSUE TITLE
Unable to use downloaded build in Chrome

### ISSUE THREAD

**Issue by daltondowning** [bvaughn/react-devtools-experimental#286]
STR:

1. Navigate to https://react-devtools-experimental-chrome.now.sh.
2. Install React DevTools by following the steps listed under "Installation instructions".

The extension is disabled upon installation and cannot be enabled:

<img width="419" alt="CleanShot 2019-05-23 at 15 11 32@2x" src="https://user-images.githubusercontent.com/18369969/58279699-16dcff00-7d6d-11e9-83bf-e7c994baad7e.png">

The [Alternative Extension Distribution Options](https://developer.chrome.com/extensions/external_extensions#prereqs) documentation from the Chrome team specifies that `.crx` files must be hosted on the Chrome Web Store in order to be used in Chrome.

Chrome: 74.0.3729.169
macOS: 10.14.5

**Comment by robertcoopercode** [comment]
I tried installing the beta devtools yesterday and couldn't get them appearing in Chrome either. I deactivated the stable version of the React Devtools and enabled the beta version in my Chrome extensions, but the `React` tab would never appear in the Chrome developer console (even after restarting Chrome).

**Comment by daltondowning** [comment]
Since @robertcoopercode wasn't able to reproduce the issue, I thought it might be an issue with my environment, so I tried with a clean Chrome profile and was able to successfully use the downloaded `.crx`. This was with Chrome version 74.0.3729.169.

I then tried with the Beta (75.0.3770.51) and Canary (76.0.3803.0) versions of Chrome with a clean profile in both and wasn't even able to download the extension. Here's the error I got:

<img width="427" alt="CleanShot 2019-05-23 at 16 34 36@2x" src="https://user-images.githubusercontent.com/18369969/58284483-b18f0b00-7d78-11e9-914b-e36cb3533f2d.png">

**Comment by bvaughn** [comment]
Canary version of Chrome doesn't seem to support self-hosted extensions. I don't know why, and it's not really something I can fix anyway. Should probably be brought up with the Chrome team rather than with me. 😄

Thanks for the detailed info, but I'm going to close this issue because I don't think troubleshooting installation issues on Beta/Canary Chrome releases is worth doing for this prerelease repo. Hopefully this extension will be stable released (in the Chrome store) soon.

**Comment by bvaughn** [comment]
I updated the Chrome installation to use a packed extension (ZIP) format rather than CRX (611fe48). Hopefully this might work for more people.
