### ISSUE TITLE
Chrome extension block:  "This extension is not listed in the Chrome Web Store and may have been added without your knowledge."

### ISSUE THREAD

**Issue by cbdeveloper** [bvaughn/react-devtools-experimental#288]
I did all the steps below, but somehow Chrome is not allowing me to enable it. Even on Dev Mode.

- download extension
- Navigate to chrome://extensions/
- Enable "Developer mode"
- Drag ReactDevTools.crx into Chrome
- Choose "Add Extension" when prompted

![image](https://user-images.githubusercontent.com/43407798/58337964-da79d380-7e3e-11e9-9635-48280e3e2681.png) 

Has this happened to anybody else?

Thanks

**Comment by daltondowning** [comment]
I experienced the [same issue](https://github.com/bvaughn/react-devtools-experimental/issues/286) yesterday. Using a clean profile in the stable version of Chrome allowed me to use the extension.

**Comment by bvaughn** [comment]
Chrome's support for self-hosted extensions is not that great. Unfortunately there's nothing I can do about it.

**Comment by bvaughn** [comment]
Sorry @cbdeveloper! Hopefully we'll get this version launched in the Chrome store soon.

**Comment by cbdeveloper** [comment]
Thanks @bvaughn ! This project is an awesome dev tool!

**Comment by dConstantineb** [comment]
你可以试试把文件解压后，通过Chrome插件管理的Load unpacked加入插件试试
