### ISSUE TITLE
Overlay stays after devtools are closed

### ISSUE THREAD

**Issue by sophiebits** [bvaughn/react-devtools-experimental#296]
1. Hover over a node so you see its bounding box over the page
2. Without moving your mouse, press Cmd-Opt-J to hide the devtools

Result: The overlay stays (even if you move your mouse or reopen React devtools!)

Expected: It disappears.

**Comment by bvaughn** [comment]
Thanks for the report, Sophie.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16485
