### ISSUE TITLE
Should be able to add a prop that is not yet set

### ISSUE THREAD

**Issue by steveluscher** [bvaughn/react-devtools-experimental#300]
Right now I can inspect a component and edit its props but I could not find a way to add a _new_ prop that wasn't already set.

**Comment by bvaughn** [comment]
Correct. That functionality is not supported by either the old or new extension.

**Comment by mountwill** [comment]
I would love to see this feature added, it's a common ask from designers using our component library.

**Comment by goxr3plus** [comment]
It is very important  actually :)

**Comment by mathieutu** [comment]
Hey. 
I've made an issue which centralized all the needs about editing interface: https://github.com/bvaughn/react-devtools-experimental/issues/367

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16484
