### ISSUE TITLE
State Not Visible in React 15.6.1 Application

### ISSUE THREAD

**Issue by agreene-coursera** [bvaughn/react-devtools-experimental#313]
I was trying out the React 15 compatible release on our logged out homepage (https://coursera.org) and noticed that none of our components' state or legacy context was being displayed. The top `SearchBar` is a stateful class component with context that you can use to reproduce.

![image](https://user-images.githubusercontent.com/30501355/59226207-51c19e00-8b87-11e9-95f2-23101c30fc09.png)

I also noticed a ~a dozen new errors in the console from what looks like a devtools file that may help with debugging. 

Example Console Error:
![image](https://user-images.githubusercontent.com/30501355/59226349-a82edc80-8b87-11e9-91b6-3cb96209d5f4.png)

The besides this issue, the new devtools look great and I'm psyched to get to start using them 😄

**Comment by bvaughn** [comment]
Thanks for the report!

cc @gaearon

**Comment by bvaughn** [comment]
Thanks for the bug report @agreene-coursera! Just deployed a fix (hopefully) to DevTools. You can pull it in by [re-installing](https://github.com/bvaughn/react-devtools-experimental#installation).

**Comment by agreene-coursera** [comment]
Happy to help, the updated version works like a charm!
