### ISSUE TITLE
Suggestion: switch between "Rendered At" renders using keyboard arrow keys

### ISSUE THREAD

**Issue by justingrant** [bvaughn/react-devtools-experimental#332]
My favorite devtools feature, "Why did this render?", has a remaining problem: it's too hard to flip through a long list of renders in the Rendered At list to find an interesting render. I know I can use the mouse (or Tab and then Space) to move to the next render, but that's painful if there are 50+ renders to work through.

Suggestion: when an item in the Rendered At list has focus, then up/down arrows should change the selected render (and scroll the pane up/down if the selected render isn't visible). 

This would be helpful for accessibility too.

I'll file a separate issue for keyboard support for the flamegraph view. Keyboard access to that view will be much harder to implement so it makes sense to do it separately.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16473
