### ISSUE TITLE
Highlight after hot reloaded

### ISSUE THREAD

**Issue by tiancihe** [bvaughn/react-devtools-experimental#338]
ENV: Chrome
ISSUE: Highlight html element after webpack hot reloaded, occurs when currently not using devtools tab, for example Network tab.
EXPECTED: Don't highlight any elements when running in the background.

**Comment by bvaughn** [comment]
Sorry, but I don't understand the bug you're reporting and there's no repro steps. Get back to me with a little more info and I'll take a look but I'm going to close for now because it's not actionable.

**Comment by tiancihe** [comment]
Sorry about the vague description, tried to repro with CRA, didn't happen no matter i use class component or function component. Maybe it is a issue with the cli i'm using ( umijs ), not sure.

![image](https://user-images.githubusercontent.com/36734012/60315458-392ff100-9999-11e9-939b-9570bcd848ba.png)

The issue is like this, everytime i modify my code, the html element gets highlighted, it's quite annoying tbh.
