### ISSUE TITLE
Error: "Could not find node with id "9193" in commit tree"

### ISSUE THREAD

**Issue by brunolemos** [bvaughn/react-devtools-experimental#339]
Was playing with the new profiler on this [project](https://github.com/devhubapp/devhub/pull/152) and got this crash. It only happened once though so it's fine.

![image](https://user-images.githubusercontent.com/619186/60275627-990e9500-98d0-11e9-879f-3bd537605282.png)

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.0-abc8ef3

Call stack: at chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:11:8479
    at Map.forEach (<anonymous>)
    at chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:11:8429
    at y.getRankedChartData (chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:11:8915)
    at Na (chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:56:248933)
    at _a (chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:43:54032)
    at El (chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:43:92125)
    at ml (chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:43:80068)
    at fl (chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:43:77229)
    at ro (chrome-extension://jmefndhcciobpfkcaeabfhkapkgbjdpm/build/main.js:43:41211)

Component stack: in Na
    in div
    in div
    in div
    in mr
    in Unknown
    in jo
    in Unknown
    in div
    in div
    in Go
    in q
    in ne
    in mo
    in Hi

**Comment by bvaughn** [comment]
Hm, so this happened after profiling? Can you give me any more info? (Any chance I could try profiling the same code to repro?)

**Comment by bvaughn** [comment]
Also, which specific version of DevTools are you using? (You can find this in chrome:extensions)

**Comment by brunolemos** [comment]
I downloaded it today:

![image](https://user-images.githubusercontent.com/619186/60291540-7476e500-98f1-11e9-83f0-785aa682353f.png)

Yeah I was profiling, checking the flamegraph. I think I tried clicking on one of the flame rows and it crashed. 

It's this branch (https://github.com/devhubapp/devhub/pull/152) but unlikely that we'll easily be able to reproduce. Just wanted to report though.

**Comment by bvaughn** [comment]
Hmm. Let me know if you see it again I guess, and have more info on how to reproduce it. I've done a lot of profiling and I haven't seen any errors recently (so I'm not confident in my ability to reproduce the problem based on the info in this task). I do appreciate the heads up though.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been merged into:
https://github.com/facebook/react/issues/16446
