### ISSUE TITLE
Getting “Profiling not supported” message sometimes

### ISSUE THREAD

**Issue by brunolemos** [bvaughn/react-devtools-experimental#343]
Sometimes I change a file, the app auto reload (using create-react-app) and I get this error message:

```
Profiling not supported.
Profiling support requires either a development or production-profiling build of React v16.5+
```

![image](https://user-images.githubusercontent.com/619186/60403359-756a7980-9b72-11e9-8db7-83cdbcc1c8a1.png)

It doesn’t happen always.
It works after I manually refresh the page:

![image](https://user-images.githubusercontent.com/619186/60403374-a8ad0880-9b72-11e9-92f3-7c816d466568.png)

![image](https://user-images.githubusercontent.com/619186/60291540-7476e500-98f1-11e9-83f0-785aa682353f.png)

**Comment by bvaughn** [comment]
Can you give a more complete repro? "_Sometimes I change a file_" is kind of...sparse. :smile:

This message is expected to be shown until a profiling-capable renderer has attached itself to DevTools.

**Comment by brunolemos** [comment]
There’s not much to add…

I use create-react-app. When I edit a file on my project, it triggers a reload in the project. 

Sometimes, on this auto reload, the profiler extension will show this message and stay at this state. I’ve got the impression this only happens on these automatic triggers, not when I manually refresh the page.

But nevermind, it only happens sometimes and it’s not critical

**Comment by bvaughn** [comment]
Ah, that's fair I guess. I just traced through the code and I'm not sure how it could get into that state, but maybe it has something to do with the hot reloading mechanism? If you're able to capture it in any form of reliable repro, let me know and I'll dig in.

Given that Dan's been completely rewriting hot reloading recently with a less hacky implementation, maybe it will also just go away.

**Comment by bvaughn** [comment]
I did give the  steps you mentioned a try FWIW but was unable to repro.
