### ISSUE TITLE
"Uncaught Error: Unsupported Bridge operation 0" on Electron's renderer devtools

### ISSUE THREAD

**Issue by kwonoj** [bvaughn/react-devtools-experimental#344]
### Repro steps ###

- clone https://github.com/kwonoj/react-exp-devtools-electron-repro
- `npm install && npm start`
- console will emit ` "Uncaught Error: Unsupported Bridge operation 0", source: chrome-extension://react-developer-tools/build/main.js (1)`
- or open up devtools for devtools via `localhost:8315`
![image](https://user-images.githubusercontent.com/1210596/60461012-2ff18f00-9bfa-11e9-8fc7-694362ffe2d6.png)

### Descriptions

- Used version `abc8ef3` of extension build

I am aware Electron is bit odd environment and probably experimental devtools have known glitches around, but couldn't figure out cause by myself and not successful to search existing issues. 

Devtools simply doesn't work on Electron environment by throwing out `Unsupported Bridge operation 0` - not sure 1. what does `0` actually means / 2. In what cases this could occur (Electron's devtools is nearly equivalent to Chromium devtools in most cases). Willing to dig deeper myself if I could have some clues or insights.

**Comment by bvaughn** [comment]
Looks like you just copied part of this repro out and tried to run it as an electron app. That's not supported. Once PR #335 has landed, a standalone version of v4 (running in Electron) will be available. Not until then though.

**Comment by kwonoj** [comment]
@bvaughn I'm not sure if I understood correctly - isn't #335 tracking `standalone` usecase? Usecase repro I created is install crx into Electron's devtools as same as install crx in chromium's devtools. Current stable react devtools supports this cases - curious if #335 intends to resolve this.

Clarify, I am not trying to run current devtools as **standalone**.

**Comment by bvaughn** [comment]
Installing the extension into an unsupported browser (anything but Chrome, Firefox, and Chromium Edge) is also not supported. The extension APIs aren't guaranteed to be the same.
