### ISSUE TITLE
Profiling doesn't work in Firefox

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#345]

**Comment by finico** [comment]
@bvaughn it seems that Safari as well

**Comment by bvaughn** [comment]
@finico There's no Safari extension. Are you referring to the alpha release of the standalone DevTools? Because profiling works for Safari for me using that version.

**Comment by finico** [comment]
@bvaughn I've tried on https://react-devtools-experimental.now.sh
Profiler shows commits but they're empty (without graph)

**Comment by bvaughn** [comment]
Ah, gotcha. Thanks for clarifying.

I guess it's not really important for Safari to support the test shell. Really that's just meant as a convenience tool for local development. I assume the underlying cause is probably the same though, so fixing the Firefox (extension) should also fix the Safari demo page :smile:

**Comment by bvaughn** [comment]
Looks like profiling is working for me on the Firefox extension, using the latest release.

**Comment by bvaughn** [comment]
The Safari issue isn't related to the Profiler. Looks like the `AutoSizer` isn't expanding to fill the parent container for some reason. (The `height` is 0 so the data just doesn't show up.)

**Comment by bvaughn** [comment]
Reload and profile seems busted in Firefox :( not sure why

**Comment by bvaughn** [comment]
Fixed 2f1c100
