### ISSUE TITLE
Expose "key" in the sidebar

### ISSUE THREAD

**Issue by probablyup** [bvaughn/react-devtools-experimental#356]
You can see it in the element tree but when you click on an element it doesn't appear in the right sidebar. It'd be awesome if it was copiable too.

**Comment by bvaughn** [comment]
The space on the right hand panel is pretty valuable. Anything we add competes for screen real estate with other things.

Legacy DevTools used to show `key` in the top of the panel, but that's the most precious space. I don't really think `key` is important enough to go there. We could inline it within props but that feels wrong too, since (at least for the time being) it is not a prop.

Why do you think it needs to be there?

**Comment by probablyup** [comment]
I regularly refer to it when debugging things like search results in some of our product views that have long key names and I'm trying to see something toward the end of the key. I'd say put it at the bottom of list of things in the panel if you want to de-emphasize it but it's currently not accessible at all.

**Comment by bvaughn** [comment]
> I regularly refer to it when debugging things like search results in some of our product views that have long key names and I'm trying to see something toward the end of the key.

It's in the Components tree though, where the search result selection is. Why isn't that sufficient?

> I'd say put it at the bottom of list of things in the panel

Putting the `key` at the bottom seems like weird placement to me.

**Comment by probablyup** [comment]
> Putting the key at the bottom seems like weird placement to me.

Just trying to offer a solution since you said the real estate is precious.

> It's in the Components tree though, where the search result selection is. Why isn't that sufficient?

If it's long key it gets ellipsed and you can't double click on it to copy/inspect it it.

**Comment by bvaughn** [comment]
> Just trying to offer a solution since you said the real estate is precious.

Understood! :smile: I just don't think that's a great alternative in this case.

> If it's a long key it gets ellipsed and you can't double click on it to copy/inspect it.

You can hover over it to see the full value (via a tooltip). How often do you actually need to copy/paste it?

**Comment by probablyup** [comment]
> You can hover over it to see the full value (via a tooltip). How often do you actually need to copy/paste it?

Thrice in the past week 😆 In my case I'm debugging a key that's actually 4 UUIDs concatenated together so it's a little unwieldy.

**Comment by bvaughn** [comment]
Maybe a compromise would be to just make _the value of key_ text-selectable, so you could double click it to select the value (in addition to hovering to see a key)

![trunc-Kapture 2019-07-31 at 14 29 15](https://user-images.githubusercontent.com/29597/62249578-986d9080-b39f-11e9-8904-273d287980b4.gif)

The downside here is that we'd have to give up our nifty (JavaScript-powered) middle text truncation but... maybe that's okay?

What do you think

**Comment by probablyup** [comment]
That makes sense to me and matches up nicely to how the normal element inspector works 👍

**Comment by bvaughn** [comment]
Cool. Thanks for talking through this.

Fixed via aed31fd.

**Comment by probablyup** [comment]
Thanks Brian!
