### ISSUE TITLE
Remember saved component filters by url or in bookmarks

### ISSUE THREAD

**Issue by 7rulnik** [bvaughn/react-devtools-experimental#359]
Hey Brian! Thank you for this devtool rewrite!
It would be cool if it will support saving filter based on url or some bookmarks. I think it will be really useful for switching between different projects. And seems that bookmarks is better solution because usually people have some diffrent stages like production/pre-production/local development.

**Comment by bvaughn** [comment]
Hmm... I understand how this could be useful! My initial reaction is that it wouldn't be worth the effort to implement+support+maintain though. Filters are quick to create and can be disabled (toggled off but still saved, so they're still around for later).

**Comment by ashsearle** [comment]
Related: without going into settings - is there any visual indication that a component filter is active?

**Comment by bvaughn** [comment]
> is there any visual indication that a component filter is active?

No, not presently.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16468
