### ISSUE TITLE
Truncation of key prop in GUI

### ISSUE THREAD

**Issue by noah79** [bvaughn/react-devtools-experimental#361]
Currently the key prop is truncated to 15 or so letters.  I've been unable to locate where in the devtools code this happens.  There is a truncateText in utils but it does not appear to be called by anyone.

![image](https://user-images.githubusercontent.com/2080870/62382842-1488e500-b514-11e9-8fc9-a92a9cd1f69b.png)

**Comment by bvaughn** [comment]
This truncation is intentional to keep nodes from being too wide (which impacts horizontal indentation).

You can hover over the key value to see the full string (as a tooltip) or double-click select it if you want to copy paste the un-truncated value though.
