### ISSUE TITLE
Improve globaly state/props edition.

### ISSUE THREAD

**Issue by mathieutu** [bvaughn/react-devtools-experimental#367]
Hi, I've seen several issues about editing props and state in devtools. As I didn't know where to put my comment, I propose to gather them together here.

For me the needed features are:
- [ ] Add new props,
- [ ] Add new entries in arrays and objects,
- [ ] Allow editing with json and not force/infer type in input.
- [x] Helpers to quick edit value (checkbox, + and - for numbers...).
- [ ] Removing entries.
- [ ] Button for cancel (+ esc), button for save (+ enter) (tab does nothing to avoid glitch).
- [ ] ... _What am I missing ? Feel free to comment with yours!_

Issues linked:
- https://github.com/bvaughn/react-devtools-experimental/issues/321
- https://github.com/bvaughn/react-devtools-experimental/issues/358
- https://github.com/bvaughn/react-devtools-experimental/issues/300
- https://github.com/bvaughn/react-devtools-experimental/issues/50

For props and state editing, we could actually take a look at what is doing for vuejs devtools, they are globally pretty amazing, and their editing interface is really cool and complete.

You can have a quick look of it here (didn't find something better right now):
https://youtu.be/odKVakhMk1o?t=1m21s

I'd be glad to help on that if I can.

Thanks for your work, 
Matt'.

**Comment by bvaughn** [comment]
As we've been talking about in #300, let's repurpose this issue to be about something specific (rather than overlapping with other issues). Happy to work with you to clean those up but I'd prefer to avoid the duplication! Mind updating the description?

**Comment by mathieutu** [comment]
Yep, doing that as soon as I can.

**Comment by bvaughn** [comment]
Closing this for now. Let's re-open individual, focused issues without overlap 😄 

(And let's do it at GitHub.com/facebook/react since that's where all issues are being migrated to)
