### ISSUE TITLE
Don't show "context" for classes without either contextType or contextTypes

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#368]
* Don't show "context" for classes without either contextType or contextTypes
* For classes with contextTypes, change the label to "legacy context" instead

**Comment by hristo-kanchev** [comment]
I'll take over this one 👍

**Comment by bvaughn** [comment]
Please hold off for now. Im in the process of merging this repo into the main React repo (https://github.com/facebook/react/pull/16381)

**Comment by hristo-kanchev** [comment]
Sure thing. 👍

**Comment by gaearon** [comment]
You can still start work and send a PR, but you'll have to re-submit it to a proper place later.

**Comment by bvaughn** [comment]
Merging might also be tricky, as a bunch of files are being moved around. Just thought it would be easier to wait a couple of days :smiles:

**Comment by gaearon** [comment]
I don't mean it would be on you to merge :-)

I'm thinking @hristo-kanchev can do the work and send a PR. Then we can ask him to copy paste the specific files he touched, find their new places in React repo, and send a PR there. That shouldn't involve puttin more work on your plate.

**Comment by bvaughn** [comment]
Nah, I didn't take it that way. I just wanted to safe Hristo the hassle of merging 😄

**Comment by hristo-kanchev** [comment]
Nice idea @gaearon . I'll prepare the code and get it ready to submit it to the main react repo.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16466
