### ISSUE TITLE
node type filtering

### ISSUE THREAD

**Issue by a-x-** [bvaughn/react-devtools-experimental#371]
add please node type filtering.

so it would be possible to:
- show all the types except HOCs, DOM-nodes
- show only app level nodes w/o library internals

**Comment by a-x-** [comment]
I see:
https://github.com/bvaughn/react-devtools-experimental/issues/231
https://github.com/bvaughn/react-devtools-experimental/pull/245

but as I understand node_modules sourced elements we cannot hide stil?

what about src/**-based  library components every project has?
e.g. we have more src/components/common components we want to hide sometimes

**Comment by a-x-** [comment]
Ok, I got. It's unexpectedly pleasure to see my dreams are realized!  thank you
<img width="393" alt="Screenshot 2019-08-09 at 12 33 52" src="https://user-images.githubusercontent.com/6201068/62769670-1f0e2600-baa2-11e9-91ca-713044217b0b.png">

**Comment by a-x-** [comment]
As I see we are currently cannot hide forwardRefs

**Comment by bvaughn** [comment]
> As I see we are currently cannot hide forwardRefs

That doesn't sound correct:

![Screen Shot 2019-08-09 at 8 48 08 AM](https://user-images.githubusercontent.com/29597/62791659-70a6b880-ba82-11e9-9a0b-1d4da0512e0d.png)

**Comment by a-x-** [comment]
I has 1/2 of shown options :-( 

I installed the extension this week
