### ISSUE TITLE
Inspecting complex values

### ISSUE THREAD

**Issue by a-x-** [bvaughn/react-devtools-experimental#374]
currently I cannot inspect even values of props

**Comment by a-x-** [comment]
![Screenshot 2019-08-09 at 14 15 54](https://user-images.githubusercontent.com/6201068/62775401-3522e300-bab0-11e9-9c8e-6184b92b4005.png)

**Comment by a-x-** [comment]
I can help if you describe the details

**Comment by bvaughn** [comment]
This is not a complete bug report. (There's no repro case.) It's not even a complete screenshot, as the bit to the left of the properties (where the expand triangle should be) is cropped out. :smile:

**Comment by a-x-** [comment]
There was no triangles in that case

I show the code later

**Comment by a-x-** [comment]
Also, allow clicking on "Object" too (and to other complex-value slugs)
