### ISSUE TITLE
can not edit state with version `2f1c100`

### ISSUE THREAD

**Issue by littlee** [bvaughn/react-devtools-experimental#379]
I have installed the `2f1c100` version, but I still can not edit state in dev tool ?

<img width="386" alt="WX20190815-171459@2x" src="https://user-images.githubusercontent.com/7534668/63085822-08c00880-bf81-11e9-95bf-056b0f741774.png">

<img width="512" alt="WX20190815-172136@2x" src="https://user-images.githubusercontent.com/7534668/63085874-28573100-bf81-11e9-8d22-a8050a73e02e.png">

**Comment by vnvizitiu** [comment]
I had the same issue, seems I wasn't running on react 16.9, you need that version to be able to edit hook states.

Hope that helps.

Thank @bvaughn for the info 😃

**Comment by littlee** [comment]
🆕 🐝 ❗️
