### ISSUE TITLE
Tooltips appear to be Times New Roman in Firefox

### ISSUE THREAD

**Issue by Daniel15** [bvaughn/react-devtools-experimental#382]
Windows Firefox:
![image](https://user-images.githubusercontent.com/91933/63136723-30669f00-bf88-11e9-9268-896f5e4ddf5e.png)

Looks OK in Chrome:
![image](https://user-images.githubusercontent.com/91933/63136731-3eb4bb00-bf88-11e9-8b1f-d7dd6f8ce629.png)

**Comment by bvaughn** [comment]
Hm. Everything _but_ the tooltips are ok? Wonder if this is an issue with @reach/tooltips.

I don't see anything funky in Firefox on the docs/demo site.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16464
