### ISSUE TITLE
An easier way to see all siblings

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#383]
I have a particular pattern that I struggle with when navigating deep trees in devtools: I want to see all siblings of a node together.

Say I'm in the middle of something and I wonder what are all nodes on the same level. It's super hard to actually get to that state. I wonder if we could tweak "left" button to do that as an intermediate state.

* first press: collapse the current node
* second press: collapse all siblings (new)
* third press: move to the parent

Maybe this is too crazy :-) Or maybe there's another mechanic that can achieve the same effect. The goal here is to be able to make sense of the tree structure by going _upwards_. Currently implementation details of children prevent me from seeing it. (At least, with the "expand" mode on — which is now on by default.)

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16463
