### ISSUE TITLE
Suspense Debugger

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#43]
### MVP
- [x] Initial prototype with a tree and toggling.
- [x] Tree should reflect real suspense state.
- [ ] Make it less fragile.
  - [x] Does findDOMNode issue affect this?
- [ ] Ensure expensive tree construction doesn't run unless you're on the tab.
- [ ] Improve navigation so the user doesn't get lost.
  - [ ] Maybe flash nodes.
  - [ ] Maybe offer a "finder" tool.
- [ ] Sync selection with the Components tab.
- [ ] Make it look nice. @bvaughn 

### Future
- [ ] Consider a fuzzer.
- [ ] Considering filtering by viewport.
- [ ] Optimize the tree updates.
  - [ ] Consider listening to operations. Don't forget to handle ancestor reorder.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16489
