### ISSUE TITLE
Can we improve cross linking between Components and Profiler?

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#56]
Profiler views aren't searchable, and so you can't easily go from a problematic component to its source code. Maybe we _could_ cross link for Fibers that happen to still be in the tree?

**Comment by gaearon** [comment]
Can it sync back selection for Fibers that are in the tree? Like, having Profiler selection change the Components selection if they're still there.

**Comment by bvaughn** [comment]
Yeah, that's what I meant by "cross link". I think syncing one way makes sense (Profiler selection changing Components tree selection) but I think that syncing the other way might be jarring/confusing.

**Comment by bvaughn** [comment]
Fixed via 0c8129c
