### ISSUE TITLE
Keep DOM Elements in sync with Components selection

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#59]
I miss the behavior of old DevTools that kept Chrome Elements and the React Components selection state in sync. I don't know how hard it would be to implement, but filing to look later.

Maybe somebody in open source can contribute?

**Comment by bvaughn** [comment]
That's what this TODO is about btw:
https://github.com/bvaughn/react-devtools-experimental/blob/bfbb4ac545514d682a330087ff4be77aeab273f1/shells/browser/shared/src/main.js#L174

**Comment by Avi98** [comment]
@bvaughn and @gaearon I would really love to contribute. If nobody is working on it, I can work on it.

**Comment by gaearon** [comment]
Sure!

**Comment by gaearon** [comment]
@Avi98 Did you get time to look into it yet? It seems pretty annoying to not have this feature so if you're busy and don't anticipate having time to build it, I'd like to get it in sooner.

**Comment by Avi98** [comment]
Hi @gaearon, I've been busy lately but got some time to dig into it. I'll be needing some more time. Meanwhile, I don't want to be a blocker, So you can take up the work.

**Comment by gaearon** [comment]
Did you manage to get something initial working? I'd like to finish this today but some pointers would be helpful.

**Comment by Avi98** [comment]
No, I have not started anything, but I was going through react-devtools  code base to find out how they were doing it and found out this code `  chrome.devtools.panels.create('React', '', 'panel.html', function(panel) {
      var reactPanel = null;
      panel.onShown.addListener(function(window) {
        // when the user switches to the panel, check for an elements tab
        // selection
        window.panel.getNewSelection();
        reactPanel = window.panel;
        reactPanel.resumeTransfer();
      });
      panel.onHidden.addListener(function() {
        if (reactPanel) {
          reactPanel.hideHighlight();
          reactPanel.pauseTransfer();
        }
      });
    });`
 see if this could be of anyhelp

**Comment by Avi98** [comment]
I have made a [gist](https://gist.github.com/Avi98/37cddcf7a486bf993d85f94c42391304)

**Comment by gaearon** [comment]
Nice, thanks

**Comment by gaearon** [comment]
https://github.com/bvaughn/react-devtools-experimental/pull/99
