### ISSUE TITLE
Unnecessary scroll up happens in some cases

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#67]
Will try to get a better repro tomorrow. For now just writing up so I don’t forget. 

I noticed that if the height is small enough, sometimes messing with items close to the end of the list abruptly scrolls me just a bit above. In other words it doesn’t let me scroll to end myself.

**Comment by bvaughn** [comment]
Could it be related to the currently selected item? The list scrolls to ensure that item is fully visible when the selection changes.

**Comment by gaearon** [comment]
I don't recall changing the selection though.

**Comment by gaearon** [comment]
Here's a gif. I'm not changing the selection, just scrolling.

![Screen Recording 2019-04-04 at 10 08 pm](https://user-images.githubusercontent.com/810438/55588670-42a51680-5726-11e9-8dd3-083449b7f87d.gif)

**Comment by bvaughn** [comment]
Ah! Related cause then:
https://github.com/bvaughn/react-devtools-experimental/blob/6c5c2cd3ad6b8978414a8e8536778521352c804f/src/devtools/views/Components/Element.js#L46-L56

**Comment by gaearon** [comment]
Yep. Looking at it, what happens is that

* Selected item goes slightly out of view.
* However, when we reach the bottom, for some reason it remounts. Maybe virtualization decides to render "last N items" where N is higher than normal count?
* Remounting causes the effect to fire again.
