### ISSUE TITLE
Uneven focus ring

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#69]
This was introduced by https://github.com/bvaughn/react-devtools-experimental/pull/53.

You can only see the unevenness when the tree is small enough to fit on a single screen:

<img width="834" alt="Screen Shot 2019-04-04 at 23 06 42" src="https://user-images.githubusercontent.com/810438/55591790-708e5900-572e-11e9-9613-8a9c89c09acc.png">

I think we can just hide that focus ring altogether, and instead either show a custom one in the right area (e.g. via focus events), or not show it altogether (somewhat worse).

An ideal version would be to show it in the right place *and* only if you navigated into the area by tabbing.

**Comment by bvaughn** [comment]
This has to do with overflow/clipping. Before I added custom `:focus` styles to e.g. the owners list, those buttons had the same problem. I'd be happy to pick this up if you'd like a hand. (Not going to touch it for the moment though, since you've self assigned it.)

**Comment by gaearon** [comment]
If you don’t mind doing it that would be great! I’m going to focus on the suspense fragment thing.

**Comment by bvaughn** [comment]
Fixed via d1a5346. Also addressed a couple of other minor keyboard navigation UX issues I noticed while testing.
