### ISSUE TITLE
Improve "owners stack" UI

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#7]
The owner stack navigation is not great when there's horizontal overflow:
![screen shot 2019-02-22 at 8 33 27 am](https://user-images.githubusercontent.com/29597/53256365-8b27d980-367c-11e9-94e1-d6a0f8e2ba0d.png)

It would be nice to use a dynamic layout that only showed the current horizontal navigation if all items fit within the available space. When items can't fit, the UI could show a more minimal form:
` [ x ]  [ ⋮ ]  LegacyContextComponent `

Clicking the "⋮" would show a drop down menu with the full list, e.g.:
```
[ x ] [ ⋮ ] LegacyContextComponent
      ┌────────────────────────┐
      │ InspectableElements    │
      │ Contexts               │
      │ LegacyContextComponent │
      └────────────────────────┘
```

**Comment by hristo-kanchev** [comment]
I'll take a look at this one over the weekend. 🎸

**Comment by hristo-kanchev** [comment]
Short demo of my work so far. 

![react tree ui](https://user-images.githubusercontent.com/23095052/54824516-7c4c3b00-4cab-11e9-8540-77dd211b1ac9.gif)

**Comment by bvaughn** [comment]
Ooh nice! That's looking promising!

**Comment by hristo-kanchev** [comment]
Hey @bvaughn.

Just letting you know that I'm still working on this.

I've been quite busy lately, so I wasn't able to give this issue much attention, all thoughI think I've identified all edge cases 🚀

**Comment by bvaughn** [comment]
No hurry. Thanks for the update.

**Comment by hristo-kanchev** [comment]
**Update**: 
This feature is almost finished. 

Just need to refactor and fix one small issue when resizing.

I made a short video if anyone is interested (feedback is greatly appreciated) to see it before I submit my PR.

[Link](https://www.youtube.com/watch?v=VGhZoPDOblI)

**Comment by bvaughn** [comment]
Looking nice!

**Comment by gaearon** [comment]
@hristo-kanchev How's it going? Want to get any help on this?

**Comment by hristo-kanchev** [comment]
Actually just finished this today 😆 

I'll be creating the PR tomorrow morning. 🚀

**Comment by bvaughn** [comment]
Hey @hristo-kanchev! The UI you shared looks great 😄 Thanks!

Before I get too deep into the PR, I wanted to ask your preference. Would you prefer I make any tweaks/edits to the PR myself? Or would you prefer I leave feedback and let you make them?

No real preference from my side. Didn't want to seem like I was asking too much by leaving requests for changes. Also didn't want to look passive aggressive by just making them myself. 😅

**Comment by bvaughn** [comment]
I've got a little time this morning to mess with it, so I think I'm going to just make a guess that it's okay for me to build on top of what you've got  😄 hope it's okay!

**Comment by hristo-kanchev** [comment]
Hey @bvaughn. 

Absolutely no problem if you want to make changes to the PR. Go for it! 🚀 

The next time I'll be able to take a look at this is probably next Friday/Saturday 😭 , so I think it would be better if you make the necessary changes.

If you don't have time, give me a shout and I'll try to find time during the working week.

Thanks!! ✋

**Comment by bvaughn** [comment]
Sounds great! Thanks!

**Comment by gaearon** [comment]
I get this on master. Is it expected?

![Screen Recording 2019-04-08 at 12 55 am](https://user-images.githubusercontent.com/810438/55691727-134a1000-5999-11e9-8aae-7517c99e5ae2.gif)

It doesn't happen every time. Happens if I enter and exit owner mode a few times.

**Comment by bvaughn** [comment]
> Is it expected?

Nope

**Comment by hristo-kanchev** [comment]
@gaearon @bvaughn I'll check it after work today. Apologies.

**Comment by bvaughn** [comment]
No worries. I probably broke it with one of my tweaks. I'll follow up tomorrow.

**Comment by hristo-kanchev** [comment]
Hey @bvaughn It seems that the changes in the `OwnerStack.css` vanished. 😆 Can you take a look? Also, It I forgot to add `max-height` the the `.Dropdown` class in the `OwnerStack.css`. Can you add that as well? Thanks!!

**Comment by bvaughn** [comment]
> Hey @bvaughn It seems that the changes in the `OwnerStack.css`

I don't know what you mean. What changes?

> Also, It I forgot to add `max-height` the the .Dropdown class in the `OwnerStack.css`

[I already added one](https://github.com/bvaughn/react-devtools-experimental/blob/e43cfa02396fa5fb00c2d23378811c1d0e54bb6b/src/devtools/views/Components/OwnersStack.css#L66) when I was tweaking things 😄
