### ISSUE TITLE
Consider adjusting scroll to preserve position when there was no user action

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#78]
Noticed this debugging DevTools itself.

While not critical, I think it would be nice if changes that were not initiated by the developer (such as actual scrolling or clicks) wouldn't cause the selected element to jump. In other words, I would expect that below the first scroll "page", prepends anywhere earlier in the tree would keep the perceived scroll position instead of shifting it up and down.

Not sure if it's inherent to the current virtual scrolling implementation or something that would be easy to fix. Maybe virtual scrolling actually makes it easier to fix because we control everything?

![Screen Recording 2019-04-06 at 03 44 pm](https://user-images.githubusercontent.com/810438/55671010-04713980-5883-11e9-825d-f098dd620e1d.gif)

**Comment by bvaughn** [comment]
My initial/gut reaction is that scroll anchoring seems kind of tricky to get right. Not sure what you're showing above (using a windowed DevTools to inspect a windowed DevTools) is all that representative of a common use case.

**Comment by gaearon** [comment]
My point wasn't to show windowed DevTools, it's just the only example I have on the non-work computer of something in a DEV mode. I don't see how "items being appended and removed above my current selection" is an uncommon case. Unless I'm missing something, this would happen in any React application all the time, depending on what I select. 

I've had similar issues debugging FB where components changing above in the tree would make the selection jump. My concern is it's disorienting. I'm not saying it's a mustfix.

If you prefer, I can keep a separate record of "not must fix" issues somewhere. I thought that it's useful to list all UX annoyances — but if this is stressful I can close and stop filing those.

**Comment by bvaughn** [comment]
> If you prefer, I can keep a separate record of "not must fix" issues somewhere. I thought that it's useful to list all UX annoyances — but if this is stressful I can close and stop filing those.

We chatted about this out of band but in case anyone sees this interaction on GH and  wonders:

I think it's good that you're filing issues to discuss ideas you have like this. 👍 

I also hope it's okay for me to respond with my honest feedback when I read them. (And hopefully it won't sound like I'm put out or being dismissive or anything. If it ever does- I apologize. That's not my intent.)

I sometimes have wary initial reactions to certain UX changes because I imagine they'll add a lot of complexity or require a lot of effort to implement, but this initial assessment isn't always correct. Sometimes it just means that I haven't considered the problem long enough or from the right angle.

**Comment by gaearon** [comment]
What if we only auto-expand the node with most weight on first render? Instead of auto-expanding all of them? Then it's less likely that random things above will be open, and the frequency of this issue will decrease.

**Comment by bvaughn** [comment]
I'm not sure what you  mean.  Can you describe with an example  tree

**Comment by gaearon** [comment]
```
<SomeApp>
  <App.Provider>
    <Router.Provider>
      <Nav /> // Collapsed by default
      <Content>
        <Body>
          <Ad />  // Collapsed by default
          <Article>
            <Stuff />
          </Article>
          <UserInfo /> // Collapsed by default
        </Body>
      </Content>
      <SomePortalThing /> // Collapsed by default
    </Router.Provider>
  </App.Provider>
</SomeApp>
```

**Comment by gaearon** [comment]
As I understand, the problem you're solving by expanding everything by default is that there's a bunch of repetitive "providers" etc which are annoying to expand if you just *want to see anything in the tree*.

The counter-point is that expanding everything makes this issue worse, and in general makes it hard to see the overall structure of the app. (You see too much detail at once.)

I'm curious if there's a compromise in the middle where we auto-expand some stuff by default, but only the "weightier" parts.

**Comment by bvaughn** [comment]
Interesting idea!

I'm a little worried that it may just feel arbitrary.

The reason I expand everything by default is that I assume when DevTools are open, you want to inspect things- and clicking to expand things individually is annoying. That being said, the inspect button is probably a more common way of jumping to an element- that or search. Still, I think there _can be_ something nice about just visually scanning a tree. So expanded-by-default _felt nicer_ to me.

Maybe we could try what you're suggesting and see what it feels like? I'm concerned  that it might feel confusing.

**Comment by gaearon** [comment]
This has been sufficiently mitigated by https://github.com/bvaughn/react-devtools-experimental/pull/168 that I feel we can close it.
