### ISSUE TITLE
When moving between deep and shallow trees, blank lines are confusing

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#8]
They're not really blank. But it would be nice if every selection change ensured the name of the currently selected component was always in the view horizontally.

![screen recording 2019-02-27 at 04 46 pm](https://user-images.githubusercontent.com/810438/53507358-a1d09500-3aaf-11e9-8d25-5194519c0331.gif)

**Comment by bvaughn** [comment]
Related to PR #1 ~ I just need to review this and think about / decide on the options param.

**Comment by bvaughn** [comment]
Fixed~

**Comment by bvaughn** [comment]
Actually it's not quite right. Re-opening for a moment.
