### ISSUE TITLE
Selecting component at the bottom causes a jump

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#80]
This only happens for components at the bottom of the scroll:

![Screen Recording 2019-04-06 at 04 27 pm](https://user-images.githubusercontent.com/810438/55671542-03430b00-5889-11e9-8d98-507bc717ac95.gif)

**Comment by gaearon** [comment]
This seems to be caused by the List border — which messes up the calculation of offsets.

**Comment by bvaughn** [comment]
Interesting! I didn't consider that aspect. I guess I can always move that border up a level
