### ISSUE TITLE
Improvements to owner stack picker

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#96]
- [x] (44ecff3) I can't seem to close it by clicking on it. I'd expect it to work, based on similar menus (like Chrome's three dots).

![](https://d2aztkdj0ezvrk.cloudfront.net/items/2S0x332r2F1w0808451K/Screen%20Recording%202019-04-08%20at%2006.49%20PM.gif?v=f24c631c)

- [x] (f1fc4b0) It would be nice if up/down arrows worked inside of it (instead of tabbing). Similar to how dropdowns are usually implemented.

- [x] (d6bd3dc) There's a weird buggy condition but I can't reproduce it now. Worth keeping an eye on: https://github.com/bvaughn/react-devtools-experimental/issues/7#issuecomment-480644081

**Comment by bvaughn** [comment]
> It would be nice if up/down arrows worked inside of it (instead of tabbing). Similar to how dropdowns are usually implemented.

Observation: Manually building/wiring up these basic interactions all over the place really sucks. This is an area begging for a better abstraction (although I haven't put much thought into what that might be yet).

**Comment by gaearon** [comment]
It's almost like something is missing in React..

**Comment by bvaughn** [comment]
PR #137 addresses the keyboard navigation issue.

**Comment by bvaughn** [comment]
I just saw the overflow bug on an internal site!

**Comment by bvaughn** [comment]
Fixed via d6bd3dc

I think this stuff has all been  addressed now~
